// AUTO-GENERATED by scaffold.sh — do not edit manually
// Chapter imports will be injected here
export const chapters: { id: string; Component: React.FC<{ step: number }>; stepCount: number }[] = [];
