// tools/puppeteer-launch.js
// 自动打开浏览器、启动 auto-play、等待播放完成
// Usage: node puppeteer-launch.js <storyboard-url> [--headed] [--screenshot-steps] [--screenshot-only] [--screenshot-dir=<dir>]

const puppeteer = require('puppeteer')
const path = require('path')
const fs = require('fs')
const { execSync } = require('child_process')

// Bring browser window to foreground (Windows-specific)
// Uses AttachThreadInput to bypass SetForegroundWindow restrictions
let _fgScriptPath = null
function bringToForeground() {
  if (process.platform !== 'win32') return
  try {
    // Write the PowerShell script once to a temp file (faster than inline each time)
    if (!_fgScriptPath) {
      _fgScriptPath = path.join(require('os').tmpdir(), 'bring-to-fg.ps1')
      fs.writeFileSync(_fgScriptPath, `
Add-Type @'
using System;
using System.Runtime.InteropServices;
public class Win32 {
  [DllImport("user32.dll")] public static extern IntPtr GetForegroundWindow();
  [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr hWnd, IntPtr lpdwProcessId);
  [DllImport("user32.dll")] public static extern bool AttachThreadInput(uint idAttach, uint idAttachTo, bool fAttach);
  [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr hWnd);
  [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
  [DllImport("kernel32.dll")] public static extern uint GetCurrentThreadId();
}
'@
$procs = Get-Process -Name msedge,chrome -ErrorAction SilentlyContinue | Where-Object { $_.MainWindowHandle -ne [IntPtr]::Zero }
foreach ($p in $procs) {
  $h = $p.MainWindowHandle
  $fg = [Win32]::GetForegroundWindow()
  $fgThread = [Win32]::GetWindowThreadProcessId($fg, [IntPtr]::Zero)
  $myThread = [Win32]::GetCurrentThreadId()
  [Win32]::AttachThreadInput($myThread, $fgThread, $true) | Out-Null
  [Win32]::ShowWindow($h, 9) | Out-Null
  [Win32]::SetForegroundWindow($h) | Out-Null
  [Win32]::AttachThreadInput($myThread, $fgThread, $false) | Out-Null
}
`)
    }
    execSync(`powershell -NoProfile -ExecutionPolicy Bypass -File "${_fgScriptPath}"`, { stdio: 'pipe', timeout: 3000 })
  } catch (e) {
    // Silently ignore - will retry on next interval
  }
}

// Load env-report.json (generated by tools/env-check.sh)
function loadEnvReport() {
  const reportPath = path.join(__dirname, '..', 'env-report.json')
  if (fs.existsSync(reportPath)) {
    try {
      return JSON.parse(fs.readFileSync(reportPath, 'utf-8'))
    } catch (e) {
      console.warn('Failed to parse env-report.json:', e.message)
    }
  }
  return null
}

// Detect screen resolution (Windows)
// Priority: env-report.json > inline PowerShell detection
function detectScreenResolution() {
  // Try env-report.json first
  const report = loadEnvReport()
  if (report && report.resolution && report.resolution.logical) {
    const res = report.resolution.logical
    // Apply even-dimension rounding (H.264 requirement)
    const [w, h] = res.split('x').map(Number)
    const adjusted = `${w - (w % 2)}x${h - (h % 2)}`
    console.log(`Screen resolution from env-report.json: ${res} -> ${adjusted}`)
    if (report.resolution.physical) {
      console.log(`Physical resolution: ${report.resolution.physical}, DPI scale: ${report.resolution.dpi_scale}x`)
    }
    return adjusted
  }

  // Fall back to inline PowerShell detection
  if (process.platform === 'win32') {
    try {
      const out = execSync(`powershell -NoProfile -Command "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Screen]::PrimaryScreen.Bounds | ForEach-Object { \\\"$($_.Width)x$($_.Height)\\\" }"`, {
        stdio: ['pipe', 'pipe', 'pipe'],
        timeout: 5000,
        encoding: 'utf-8'
      }).trim()
      if (out && /^\d+x\d+$/.test(out)) {
        // H.264 requires even dimensions, round down to nearest even
        const [w, h] = out.split('x').map(Number)
        const evenW = w - (w % 2)
        const evenH = h - (h % 2)
        const adjusted = `${evenW}x${evenH}`
        console.log(`Detected screen resolution: ${out} -> adjusted to ${adjusted} (even dimensions)`)
        return adjusted
      }
    } catch (e) {
      console.warn('PowerShell resolution detection failed:', e.message)
    }
  }
  // macOS / Linux / fallback
  return '1920x1080'
}

// Detect available browser: Chrome → Edge (Chromium-based) → default
// Priority: env-report.json > inline path detection
function detectBrowserPath() {
  // Try env-report.json first
  const report = loadEnvReport()
  if (report && report.browser && report.browser.path && report.browser.detected) {
    console.log(`Browser from env-report.json: ${report.browser.path}`)
    return report.browser.path
  }

  // Fall back to inline detection
  const candidates = [
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
  ]
  for (const p of candidates) {
    if (fs.existsSync(p)) return p
  }
  return undefined
}

async function launch(url, headed = false, options = {}) {
  const { screenshotSteps = false, screenshotOnly = false, screenshotDir = null } = options

  // Detect screen resolution for window sizing
  const resolution = detectScreenResolution()
  const [scrW, scrH] = resolution.split('x').map(Number)

  const launchOptions = {
    headless: headed ? false : 'new',
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-infobars',
      '--no-first-run',
      '--disable-prompt-on-repost',
      '--disable-background-timer-throttling',
    ],
    defaultViewport: null,  // Use actual window size as viewport
  }
  const browserPath = process.env.PUPPETEER_EXECUTABLE_PATH || detectBrowserPath()
  if (browserPath) {
    launchOptions.executablePath = browserPath
    console.log(`Using browser: ${browserPath}`)
  }

  const browser = await puppeteer.launch(launchOptions)
  let fgInterval = null

  try {
    const page = await browser.newPage()

    // Force browser window to cover full screen via CDP
    try {
      const session = await page.target().createCDPSession()
      const { windowId } = await session.send('Browser.getWindowForTarget')
      await session.send('Browser.setWindowBounds', {
        windowId,
        bounds: { left: 0, top: 0, width: scrW, height: scrH, windowState: 'maximized' }
      })
      console.log(`Browser window maximized via CDP (${scrW}x${scrH})`)
    } catch (e) {
      console.warn('CDP window bounds failed:', e.message)
    }

    // Bring browser to foreground (critical for screen capture)
    bringToForeground()

    // Wait a moment for the window to fully appear and stabilize
    await new Promise(r => setTimeout(r, 2000))

    // Bring to foreground again after page loads
    bringToForeground()

    // Periodic foreground activation every 2 seconds (prevents focus loss during auto-play)
    fgInterval = setInterval(() => bringToForeground(), 2000)

    // Get actual browser viewport size (may differ from screen resolution due to title bar, borders)
    const actualViewport = await page.evaluate(() => ({
      width: window.innerWidth,
      height: window.innerHeight
    }))
    console.log(`Actual browser viewport: ${actualViewport.width}x${actualViewport.height}`)
    console.log(`Screen resolution: ${scrW}x${scrH}`)
    // Write viewport dimensions to temp file for render-video.sh to read
    const viewportFile = path.join(process.cwd(), '.viewport-dimensions.txt')
    fs.writeFileSync(viewportFile, `${actualViewport.width}x${actualViewport.height}`)
    console.log(`Viewport dimensions saved to: ${viewportFile}`)

    console.log(`Opening: ${url}`)
    await page.goto(url, { waitUntil: 'networkidle0', timeout: 30000 })

    // Wait for React to render
    await page.waitForSelector('#root', { timeout: 10000 })

    // Check if auto mode overlay is showing
    const hasOverlay = await page.evaluate(() => {
      return document.body.textContent.includes('Press SPACE to start')
    })

    if (!hasOverlay) {
      console.log('WARN: Auto mode overlay not found, page may not support ?auto=1')
    }

    // Resolve screenshot directory (default: workspace/storyboard/screenshots)
    const outDir = screenshotDir || path.join(process.cwd(), 'storyboard', 'screenshots')

    // --- Screenshot-only mode: capture each step without auto-play ---
    if (screenshotOnly) {
      fs.mkdirSync(outDir, { recursive: true })
      console.log('Screenshot-only mode: capturing steps...')

      // Press SPACE to dismiss overlay
      await page.keyboard.press('Space')
      await new Promise(r => setTimeout(r, 500))

      let stepIndex = 0
      const MAX_STEPS = 100  // safety limit
      let prevProgress = null

      for (let i = 0; i < MAX_STEPS; i++) {
        await new Promise(r => setTimeout(r, 500))
        const stepFile = path.join(outDir, `step-${String(stepIndex).padStart(2, '0')}.png`)
        await page.screenshot({ path: stepFile, fullPage: false })
        console.log(`[SCREENSHOT] ${stepFile}`)
        stepIndex++

        // Check if we're at the end (progress bar at 100%)
        const progress = await page.evaluate(() => {
          const bar = document.querySelector('.cd-progress-bar')
          return bar ? bar.style.width : null
        }).catch(() => null)

        if (progress === '100%' && prevProgress === '100%') {
          break  // stable at end
        }
        prevProgress = progress

        await page.keyboard.press('Space')
      }

      console.log(`Screenshot capture complete: ${stepIndex} steps`)
      return  // finally block handles clearInterval + browser.close()
    }

    // --- Normal auto-play mode (with optional per-step screenshots) ---
    if (screenshotSteps) {
      fs.mkdirSync(outDir, { recursive: true })
    }

    // Press SPACE to start
    console.log('Pressing SPACE to start auto-play...')
    await page.keyboard.press('Space')

    // Capture first step screenshot if enabled
    if (screenshotSteps) {
      await new Promise(r => setTimeout(r, 500))
      const stepFile = path.join(outDir, 'step-00.png')
      await page.screenshot({ path: stepFile, fullPage: false })
      console.log(`[SCREENSHOT] ${stepFile}`)
    }

    // Wait for auto-play to complete
    // Strategy: poll for the page to signal completion
    // The app plays audio per step and advances. When the last step's audio ends,
    // the app stays on the final step. We detect this by watching for stability.
    console.log('Waiting for auto-play to complete...')

    let stableCount = 0
    let screenshotIndex = 1
    const MAX_WAIT_MS = 10 * 60 * 1000 // 10 minutes
    const startTime = Date.now()

    while (stableCount < 10 && Date.now() - startTime < MAX_WAIT_MS) {
      await new Promise(r => setTimeout(r, 1000))

      // Try to detect current step from the page
      const currentStep = await page.evaluate(() => {
        // Look for progress bar or step indicator
        const bar = document.querySelector('.cd-progress-bar')
        if (bar) {
          const width = bar.style.width
          return width // e.g., "100%" for last step
        }
        return null
      }).catch((err) => {
        console.warn('Poll evaluate failed:', err.message)
        return null
      })

      if (currentStep === '100%') {
        stableCount++
      } else {
        // Capture per-step screenshot when step changes
        if (screenshotSteps && currentStep) {
          const stepFile = path.join(outDir, `step-${String(screenshotIndex).padStart(2, '0')}.png`)
          await page.screenshot({ path: stepFile, fullPage: false })
          console.log(`[SCREENSHOT] ${stepFile}`)
          screenshotIndex++
        }
        stableCount = 0
        // Re-activate browser foreground on each step transition (prevents focus loss during page changes)
        bringToForeground()
      }
    }

    if (stableCount < 10) {
      throw new Error('Auto-play timed out after 10 minutes')
    }

    // Capture final step screenshot
    if (screenshotSteps) {
      const stepFile = path.join(outDir, `step-${String(screenshotIndex).padStart(2, '0')}.png`)
      await page.screenshot({ path: stepFile, fullPage: false })
      console.log(`[SCREENSHOT] ${stepFile}`)
    }

    console.log('Auto-play complete')
  } finally {
    clearInterval(fgInterval)
    await browser.close()
    console.log('Browser closed')
  }
}

const args = process.argv.slice(2)
const url = args.find(a => !a.startsWith('--'))
const headed = args.includes('--headed')
const screenshotSteps = args.includes('--screenshot-steps')
const screenshotOnly = args.includes('--screenshot-only')
const screenshotDir = args.find(a => a.startsWith('--screenshot-dir='))?.split('=')[1] || null

if (!url) {
  console.error('Usage: node puppeteer-launch.js <storyboard-url> [--headed] [--screenshot-steps] [--screenshot-only] [--screenshot-dir=<dir>]')
  process.exit(1)
}

launch(url, headed, { screenshotSteps, screenshotOnly, screenshotDir }).catch(err => {
  console.error('Failed:', err.message)
  process.exit(1)
})
