#!/bin/bash
# skills/storyboard/scaffold.sh
# 从 skeleton 创建 storyboard 项目，注入 outline 数据
# Usage: bash scaffold.sh <workspace-dir> [theme-id]

set -euo pipefail

WORKSPACE="${1:?Usage: scaffold.sh <workspace-dir> [theme-id]}"
THEME="${2:-paper-press}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKELETON="$SCRIPT_DIR/skeleton"
STORYBOARD_DIR="$WORKSPACE/storyboard"
OUTLINE="$WORKSPACE/distill/outline.md"

if [ ! -f "$OUTLINE" ]; then
  echo "ERROR: $OUTLINE not found" >&2
  exit 1
fi

# Step 1: 复制 skeleton（排除 node_modules 加速，然后 npm install）
echo "Copying skeleton..."
mkdir -p "$STORYBOARD_DIR"
if command -v rsync >/dev/null 2>&1; then
  rsync -a --exclude='node_modules' "$SKELETON/" "$STORYBOARD_DIR/"
else
  # Fallback: cp -r then remove node_modules if copied
  cp -r "$SKELETON/." "$STORYBOARD_DIR/"
  rm -rf "$STORYBOARD_DIR/node_modules"
fi

# Step 2: 安装依赖
echo "Installing dependencies..."
cd "$STORYBOARD_DIR" && npm install --silent 2>/dev/null

# Step 3: 解析 outline.md 提取章节信息
# 格式: ## N. <id> — <title>（<S> steps · ~<T>s）
declare -a CHAPTER_IDS=()
declare -a CHAPTER_TITLES=()
declare -a CHAPTER_STEPS=()

while IFS= read -r line; do
  if echo "$line" | grep -qE '^## [0-9]+\. '; then
    ch_id=$(echo "$line" | sed -E 's/^## [0-9]+\. ([a-z-]+) —.*/\1/')
    ch_title=$(echo "$line" | sed -E 's/^## [0-9]+\. [a-z-]+ — (.+?)（.*/\1/')
    ch_steps=$(echo "$line" | grep -oE '[0-9]+ steps' | grep -oE '[0-9]+')

    CHAPTER_IDS+=("$ch_id")
    CHAPTER_TITLES+=("$ch_title")
    CHAPTER_STEPS+=("$ch_steps")
  fi
done < "$OUTLINE"

NUM_CHAPTERS=${#CHAPTER_IDS[@]}
echo "Found $NUM_CHAPTERS chapters"

# Step 4: 为每章创建目录和 narrations.ts
CSS_IMPORTS=""
CHAPTER_IMPORTS=""
CHAPTER_REGISTRATIONS=""

for i in "${!CHAPTER_IDS[@]}"; do
  idx=$(( i + 1 ))
  ch_id="${CHAPTER_IDS[$i]}"
  ch_title="${CHAPTER_TITLES[$i]}"
  ch_steps="${CHAPTER_STEPS[$i]}"
  padded=$(printf "%02d" "$idx")
  dir_name="${padded}-${ch_id}"
  chapter_dir="$STORYBOARD_DIR/src/chapters/$dir_name"

  mkdir -p "$chapter_dir"

  # 从 outline 提取该章的口播节选作为 narrations
  narration_text=$(sed -n "/^## ${idx}\./,/^## [0-9]\+\./{/^\*\*口播节选\*\*/s/.*：//p;}" "$OUTLINE" | head -1)

  cat > "$chapter_dir/narrations.ts" << NARRATIONS_EOF
export const narrations = [
  "${narration_text}",
];
NARRATIONS_EOF

  # 创建占位 Chapter.tsx
  component_name="Chapter$(printf "%02d" "$idx")"
  cat > "$chapter_dir/Chapter.tsx" << CHAPTER_EOF
import { narrations } from './narrations';

interface ChapterProps { step: number; }

export function ${component_name}({ step }: ChapterProps) {
  // TODO: Implement ${ch_title} chapter
  return <div style={{ width: 1920, height: 1080, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 48, fontFamily: 'var(--font-display-cn)' }}>
    ${ch_title} — step {step}
  </div>;
}
CHAPTER_EOF

  # 创建空的 Chapter.css
  prefix="c${padded}"
  cat > "$chapter_dir/Chapter.css" << CSS_EOF
/* Chapter ${padded} — ${ch_id}: ${ch_title} */
/* Prefix: ${prefix}- */
.${prefix}-stage {
  width: 1920px;
  height: 1080px;
  background: var(--shell);
  color: var(--text);
  font-family: var(--font-display-cn);
  padding: 80px;
}
CSS_EOF

  # 累积 imports
  CSS_IMPORTS="${CSS_IMPORTS}import './chapters/${dir_name}/Chapter.css'\n"
  CHAPTER_IMPORTS="${CHAPTER_IMPORTS}import { ${component_name} } from './chapters/${dir_name}/Chapter';\n"
  CHAPTER_REGISTRATIONS="${CHAPTER_REGISTRATIONS}  { id: '${dir_name}', Component: ${component_name}, stepCount: ${ch_steps} },\n"
done

# Step 5: 注入 chapters.ts
cat > "$STORYBOARD_DIR/src/chapters.ts" << EOF
// AUTO-GENERATED by scaffold.sh
$(echo -e "$CHAPTER_IMPORTS")

export const chapters = [
$(echo -e "$CHAPTER_REGISTRATIONS")
];
EOF

# Step 6: 注入 main.tsx（重写，注入 CSS imports）
cat > "$STORYBOARD_DIR/src/main.tsx" << EOF
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './theme.css'
import './App.css'
$(echo -e "$CSS_IMPORTS")
import App from './App'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
EOF

# Step 7: 设置主题
echo "Theme: $THEME"

echo "Scaffold complete: $STORYBOARD_DIR"
echo "   Chapters: $NUM_CHAPTERS"
for i in "${!CHAPTER_IDS[@]}"; do
  padded=$(printf "%02d" $(( i + 1 )))
  echo "   ${padded}. ${CHAPTER_IDS[$i]} — ${CHAPTER_TITLES[$i]} (${CHAPTER_STEPS[$i]} steps)"
done
echo ""
echo "Next: Agent fills in Chapter.tsx for each chapter"
